name: CI

on:
  push:
    branches:
      - '*'
    tags:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ['7.2', '7.3', '7.4']
        es: ['7.1.1', '7.2.1', '7.3.2', '7.4.2', '7.5.1']
    name: PHP ${{ matrix.php }} with ES ${{ matrix.es }}
    steps:
    - uses: actions/checkout@v1
    - name: Configure sysctl limits
      run: |
        sudo swapoff -a
        sudo sysctl -w vm.swappiness=1
        sudo sysctl -w fs.file-max=262144
        sudo sysctl -w vm.max_map_count=262144
    - uses: getong/elasticsearch-action@v1.2
      with:
        elasticsearch version: '${{ matrix.es }}'
        host port: 9200
        container port: 9200
        host node port: 9300
        node port: 9300
        discovery type: 'single-node'
    - uses: actions/cache@v1
      name: Cache dependencies
      with:
        path: ~/.composer/cache/files
        key: composer-php-${{ matrix.php }}-${{ hashFiles('composer.json') }}
    - name: Install dependencies
      run: |
        composer install --no-interaction --no-interaction --prefer-source
    - name: Wait for Elasticsearch to be ready
      run: |
        until curl --silent -XGET --fail http://127.0.0.1:9200; do printf '.'; sleep 1; done
    - name: Run tests for Simple Indexer
      run: |
        export SCOUT_ELASTICSEARCH_INDEXER_CLASS="\Rennokki\ElasticScout\Indexers\SimpleIndexer"
        phpunit --coverage-text --coverage-clover=coverage_simple.xml
    - name: Run tests for Multiple Indexer
      run: |
        export SCOUT_ELASTICSEARCH_INDEXER_CLASS="\Rennokki\ElasticScout\Indexers\MultipleIndexer"
        phpunit --coverage-text --coverage-clover=coverage_multiple.xml
    - uses: codecov/codecov-action@v1
      with:
        fail_ci_if_error: true
        file: '*.xml'
